hw003
Plyushchenko/JVM pull request #2
Opened 2017-09-25 01:16 UTC by Plyushchenko

Username: @GuessTheNumberHWBot

2017-09-25 08:55 UTC, adkozlov commented
Добавьте, пожалуйста, @dzharkov в качестве ревьюера.

2017-10-07 20:10 UTC, adkozlov commented
Ping, @Plyushchenko.

2017-10-08 10:05 UTC, Plyushchenko commented
@adkozlov 
https://pp.userapi.com/c841421/v841421090/29d5a/gekdo4iGY4s.jpg

2017-10-14 12:26 UTC, dzharkov requested changes
Жду исправлений и ответов на вопросы 17.10 23:59. Не забудь написать “@dzharkov” в комменте к PR

2017-10-14 12:26 UTC, dzharkov commented on hw003/src/main/scala/GuessTheNumber/bot/GuessTheNumberBot.scala
> +        case Success(Stats((x, y))) => reply("+ " + x + "\n- " + y + "\n% " + 100d * x / (x + y))
1. Из кода не очень понятно, что такое x, y
2. Вычисления процентов тоже лучше вынести в переменную или функцию для облегчения чтения
3. Используйте string interpolation

2017-10-14 12:26 UTC, dzharkov commented on hw003/src/main/scala/GuessTheNumber/bot/GuessTheNumberBot.scala
> +  onMessage {
А можно написать бота, который будет наоборот, отгадывать число?)

2017-10-17 15:29 UTC, Plyushchenko commented on hw003/src/main/scala/GuessTheNumber/bot/GuessTheNumberBot.scala
> +  onMessage {
Да, можно.

2017-10-17 16:23 UTC, Plyushchenko commented
@dzharkov

2017-12-01 12:51 UTC, Plyushchenko commented
@dzharkov

2017-12-03 12:04 UTC, Plyushchenko commented
@adkozlov 
@dzharkov 
Там ещё и 0 в таблице красуется, я ничего не понимаю.

2017-12-03 18:10 UTC, dzharkov commented
Извиняюсь, но что-то я пропустил эти реквесты
Ок, 10/10

2017-12-03 21:51 UTC, closed without merging